hougesen/mdsf

- .github/workflows/validate.yml
- README.md
- schemas/v0.0.0/mdsf.schema.json
- src/config.rs
- src/formatters/mix_format.rs
- src/formatters/mod.rs
- src/formatters/rubocop.rs
- src/languages/mod.rs
- src/languages/ruby.rs
- tests/ruby.md
> feat(ruby): add support for rubocop

- .github/workflows/validate.yml
- src/formatters/mod.rs
- src/formatters/yamlfmt.rs
- src/languages/yaml.rs
> feat(yaml): add support for yamlfmt

- README.md
- schemas/v0.0.2/mdsf.schema.json
- src/config.rs
- src/formatters/erlfmt.rs
- src/formatters/mod.rs
- src/languages/erlang.rs
- src/languages/mod.rs
> feat(erlang): support erlfmt

- README.md
- schemas/v0.0.2/mdsf.schema.json
- src/formatters/ktfmt.rs
- src/formatters/mod.rs
- src/languages/kotlin.rs
> feat(kotlin): add support for ktfmt

- README.md
- schemas/v0.0.2/mdsf.schema.json
- src/config.rs
- src/formatters/fantomas.rs
- src/formatters/mod.rs
- src/languages/fsharp.rs
- src/languages/mod.rs
> feat(fsharp): add support for fantomas

- .github/workflows/validate.yml
- .gitignore
- README.md
- schemas/v0.0.2/mdsf.schema.json
- src/formatters/csharpier.rs
- src/formatters/mod.rs
- src/formatters/usort.rs
- src/languages/csharp.rs
> feat(csharp): add support for csharpier

- README.md
- schemas/v0.0.2/mdsf.schema.json
- src/formatters/mod.rs
- src/languages/protobuf.rs
> feat(protobuf): add support for buf

- justfile
- src/formatters/biome.rs
- src/formatters/clang_format.rs
- src/formatters/deno_fmt.rs
- src/formatters/mod.rs
- src/formatters/prettier.rs
- src/languages/json.rs
- src/languages/mod.rs
- src/lib.rs
> feat(json): add internal support for json, jsonc and json5

- README.md
- schemas/v0.0.3/mdsf.schema.json
- src/formatters/mod.rs
- src/formatters/standardjs.rs
- src/languages/javascript.rs
- tests/go.md
> feat(javascript): add support for standardjs

- .github/workflows/validate.yml
- src/formatters/prettier.rs
- src/languages/css.rs
- src/languages/graphql.rs
- src/languages/html.rs
- src/languages/javascript.rs
- src/languages/json.rs
- src/languages/markdown.rs
- src/languages/typescript.rs
- src/languages/vue.rs
- src/languages/yaml.rs
Enable embedded_language_formatting if file is not markdown
> refactor(prettier): enable embed fmt based on ft

- src/cli.rs
The schema command is only used internally to generate json schema. No reason to expose it publicly.
> chore(cli): hide schema command

- Cargo.lock
- Cargo.toml
- codegen/Cargo.lock
- src/error.rs
- src/formatters/mod.rs
- src/terminal/mod.rs
Adds a line of `-` before and after stderr when running using `--debug`.
> feat: add line between stderr output

- Cargo.lock
- Cargo.toml
- codegen/Cargo.lock
- src/caching.rs
Switch to sha256 for cache key hashing
> refactor: use sha256 instead of built in hash

- .github/workflows/codegen.yml
2 runs of codegen is needed until readme table generation is decoupled from the json-schema
> ci: run codegen twice

- .github/dependabot.yml
- .gitignore
- justfile
- mdsf-vscode/.gitignore
- mdsf-vscode/.npmrc
- mdsf-vscode/.vscode-test.mjs
- mdsf-vscode/.vscode/extensions.json
- mdsf-vscode/.vscode/launch.json
- mdsf-vscode/.vscode/settings.json
- mdsf-vscode/.vscode/tasks.json
- mdsf-vscode/.vscodeignore
- mdsf-vscode/CHANGELOG.md
- mdsf-vscode/README.md
- mdsf-vscode/biome.json
- mdsf-vscode/esbuild.js
- mdsf-vscode/eslint.config.mjs
- mdsf-vscode/package.json
- mdsf-vscode/pnpm-lock.yaml
- mdsf-vscode/src/extension.ts
- mdsf-vscode/src/test/extension.test.ts
- mdsf-vscode/tsconfig.json
- mdsf-vscode/vsc-extension-quickstart.md
The aim of this pr is to create a simple vs code extension that allows the user to format their markdown files using mdsf.
For now the extension requires that the user has mdsf installed through other means. In the future it would be nice to automatically install/bundle mdsf with the extension.
Closes #389 on merge.
> feat: mdsf vscode extension

- README.md
- schemas/v0.5.2-dev/mdsf.schema.json
- tools/runic/plugin.json
Adds support for the Julia formatter Runic https://github.com/fredrikekre/Runic.jl
> feat(cli): add support for runic

- .github/workflows/test.yml
- codegen/src/actions/packages.rs
I have changed the order of test install steps since Go compiles the package from scratch
> test: decrease go install priority

- mdsf/src/execution/mod.rs
I accidentally flipped the boolean 🤫
> fix: only print tool stdout/stderr when debug is enabled

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- codegen/Cargo.toml
- codegen/src/error/mod.rs
- codegen/src/language_to_filetype.rs
Switch to ureq to reduce compiletime of clean builds
> refactor(codegen): use ureq instead of reqwest

- .github/workflows/release.yml
- CHANGELOG.md
- dist-workspace.toml
The `ubuntu-20.04` action image was removed yesterday which makes this a high priority.
`cargo-dist`, the release build system used by mdsf, has sadly lost funding (?) which has resulted in project development being paused (?) and no official fix being provided (yet?). 
The changes in `dist-workspace.toml` should be rolled back once https://github.com/axodotdev/cargo-dist/issues/1760 is fixed, or a suitable fork is found.
[astral-sh/cargo-dist](https://github.com/astral-sh/cargo-dist/) seems like it could be a good alternative, but we have yet to see if Astral is interested in actually support a community around the fork.
> fix(cargo-dist): manually set gh action runs-on to ubuntu-latest

- CHANGELOG.md
- mdsf/tests/tooling.rs
- tools/tombi/plugin.json
Tests were disabled because of an issue with schemastore
> test(tools): enable tombi tests again

- CHANGELOG.md
- README.md
- mdsf/src/tools/mod.rs
- mdsf/src/tools/tombi_format.rs
- schemas/development/mdsf.schema.json
- schemas/v0.9.7-next/mdsf.schema.json
- tools/tombi/plugin.json
Tombi recently made a change that resulted in files in /tmp/ being ignored. This should fix it.
> refactor(tombi): use stdin when formatting using tombi

- mdsf-vscode/src/extension.ts
Rename 'err' event to 'error' in extension.ts.
Result: 
Closes #1270
> fix(mdsf-vscode): fix mdsf-vscode error log
