.github/workflows/validate.yml, README.md, schemas/v0.0.0/mdsf.schema.json, src/formatters/black.rs, src/formatters/mod.rs, src/languages/python.rs
=> feat(python): support black

.github/workflows/validate.yml, README.md, schemas/v0.0.0/mdsf.schema.json, src/formatters/autopep8.rs, src/formatters/blue.rs, src/formatters/mod.rs, src/formatters/yapf.rs, src/languages/python.rs
Closes #18
Closes #42 
Closes  #16
=> feat(python): add support for blue, yapf and autopep8

.github/workflows/validate.yml, Makefile, schemas/v0.0.1/mdsf.schema.json, src/formatters/isort.rs, src/formatters/mod.rs, src/languages/python.rs
=> feat(python): add support for isort

.github/workflows/validate.yml, schemas/v0.0.1/mdsf.schema.json, src/formatters/mod.rs, src/formatters/usort.rs, src/languages/python.rs
=> feat(python): support usort

README.md, schemas/v0.0.1/mdsf.schema.json, src/config.rs, src/formatters/biome.rs, src/formatters/elm_format.rs, src/formatters/mod.rs, src/formatters/prettier.rs, src/formatters/sql_formatter.rs, src/formatters/stylua.rs, src/formatters/taplo.rs, src/languages/elm.rs, src/languages/mod.rs, src/runners/mod.rs
=> feat(elm): support elm-format

src/cli.rs, src/formatters/mod.rs, src/lib.rs, src/main.rs
Added debug flag that turns on/off stdout&stderr of formatters
=> feat: add debug flag

schemas/v0.0.2/mdsf.schema.json, src/formatters/mod.rs, src/languages/json.rs, src/lib.rs, src/main.rs
Move people use prettier so it makes sense to use that first
=> fix(json): try prettier before biome

src/formatters/mod.rs, src/formatters/rubyfmt.rs, src/languages/ruby.rs
=> feat(ruby): add support for rubyfmt

src/formatters/luaformatter.rs, src/formatters/mod.rs, src/languages/lua.rs
=> feat(lua): add support for luaformatter

.github/workflows/validate.yml, src/formatters/mod.rs, src/formatters/standardrb.rs, src/languages/ruby.rs
=> feat(ruby): add support for standardrb

src/lib.rs
=> refactor(parser): disable smart punctuation

Cargo.lock, Cargo.toml, src/formatters/mod.rs, src/lib.rs, src/main.rs
=> refactor(parser): implement custom markdown parser

src/lib.rs
=> fix: print correct elapsed time

.prettierrc, mdsf.json, schemas/v0.0.3/mdsf.schema.json, scripts/update-supported-languages.mjs, src/config.rs, src/formatters/biome.rs, src/formatters/blade_formatter.rs, src/formatters/elm_format.rs, src/formatters/npm_groovy_lint.rs, src/formatters/prettier.rs, src/formatters/purs_tidy.rs, src/formatters/rescript_format.rs, src/formatters/sql_formatter.rs, src/formatters/stylua.rs, src/formatters/taplo.rs, src/languages/elm.rs, src/lib.rs, src/main.rs, src/runners/mod.rs, src/terminal/mod.rs
=> feat: add support for choosing npm script runner (npx, bunx, deno)

.prettierrc, src/languages/mod.rs, src/lib.rs, tests/go.md
=> feat(go): add temporary package name if missing

Cargo.lock, Cargo.toml, src/formatters/mod.rs, src/formatters/prettier.rs, src/terminal/mod.rs
Validate that binary exists before execution. 
Related to #43
=> feat: check if binary in path before use

src/formatters/beautysh.rs, src/formatters/mod.rs, src/formatters/shfmt.rs, src/languages/mod.rs, src/languages/shell.rs
=> feat(shell): support sh, bash and zsh

.github/workflows/validate.yml, README.md, mdsf.json, schemas/v0.0.3/mdsf.schema.json, src/config.rs, src/formatters/alejandra.rs, src/formatters/mod.rs, src/formatters/nixfmt.rs, src/formatters/nixpkgs_fmt.rs, src/languages/mod.rs, src/languages/nix.rs
=> feat(nix): add support for nixfmt and alejandra

README.md
=> docs: add alternatives

src/cli.rs, src/languages/mod.rs, src/terminal/mod.rs
Log time taken by each formatter (TRACE).
=> chore: log formatter time taken

src/cli.rs, src/error.rs, src/lib.rs, src/main.rs, src/terminal/mod.rs
Add command for verifying files are formatted.
Closes #201.
=> feat: add verify command

README.md, schemas/v0.0.7/mdsf.schema.json, src/formatters/misspell.rs, src/formatters/mod.rs, src/languages/markdown.rs
=> feat: support misspell

src/formatters/codespell.rs
=> refactor(codespell): enable autofixing

src/formatters/typos.rs
=> fix(typos): enable autofixing

src/formatters/misspell.rs
=> refactor(misspell): enable autofixing

README.md, schemas/v0.0.7/mdsf.schema.json, src/formatters/golines.rs, src/formatters/mod.rs, src/languages/go.rs
=> feat(go): support golines

Cargo.lock, Cargo.toml, README.md, src/cli.rs, src/formatters/biome.rs, src/formatters/blade_formatter.rs, src/lib.rs, src/main.rs
Added command for shell completion for bash, zsh, elvish, powershell and fish.
=> feat: shell completion command

README.md, schemas/v0.1.2/mdsf.schema.json, src/formatters/dotenv_linter.rs, src/formatters/mod.rs
=> feat: support dotenv-linter

Cargo.lock, Cargo.toml, codegen/Cargo.lock, src/cli.rs, src/commands/format.rs, src/formatters/mod.rs, src/lib.rs, src/terminal/mod.rs
=> feat: add support for multithreading

src/formatters/veryl.rs
requires a Veryl.toml file to work
=> test: verify veryl fmt works

mdsf/src/lib.rs, mdsf/src/parser/mod.rs
=> fix: respect existing codeblock indentation

mdsf/src/cli.rs, mdsf/src/commands/mod.rs
=> fix: set default log level to debug

README.md, mdsf/src/tools/gci.rs, schemas/v0.4.2-dev/mdsf.schema.json
There was a typo in the --skip-vendor flag
=> fix: gci formatter

README.md, mdsf/src/tools/mdsf_check.rs, mdsf/src/tools/mdsf_format.rs, mdsf/src/tools/mod.rs, schemas/development/mdsf.schema.json, schemas/v0.7.0-next/mdsf.schema.json, tools/mdsf/plugin.json
Adds support for running mdsf as a command using mdsf.
=> feat(tools): run mdsf using mdsf

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, mdsf/Cargo.toml, mdsf/src/cli.rs, mdsf/src/commands/format.rs, mdsf/src/config.rs, mdsf/src/error.rs, mdsf/src/lib.rs, mdsf/src/terminal/mod.rs, mdsf/src/testing/mod.rs, mdsf/tests/main.rs, schemas/development/mdsf.schema.json, schemas/v0.8.5-next/mdsf.schema.json
=> feat(cli): argument for erroring on missing language definition

CHANGELOG.md, README.md
As mentioned by @ccoVeille 
https://github.com/hougesen/mdsf/issues/618#issuecomment-2830909748
=> docs: usage of config.language_aliases

CHANGELOG.md, mdsf/src/config.rs, mdsf/src/execution/mod.rs, mdsf/src/lib.rs, mdsf/src/parser/mod.rs, mdsf/src/terminal/mod.rs, schemas/development/mdsf.schema.json, schemas/v0.9.1-next/mdsf.schema.json
As mentioned here https://github.com/hougesen/mdsf/pull/984#pullrequestreview-2796175468
=> refactor(config): rename line_endings to newline

.github/workflows/test.yml, README.md, mdsf/src/tools/mod.rs, mdsf/src/tools/pyrefly.rs, mdsf/tests/tooling.rs, schemas/development/mdsf.schema.json, schemas/v0.9.4-next/mdsf.schema.json, tools/pyrefly/plugin.json
Adds support for the new Python typechecker Pyrefly https://github.com/facebook/pyrefly
=> feat(tools): support pyrefly

.github/workflows/test.yml, CHANGELOG.md, README.md, mdsf-vscode/.gitignore, mdsf-vscode/package.json, mdsf/src/tools/mod.rs, mdsf/src/tools/tombi_format.rs, mdsf/src/tools/tombi_lint.rs, mdsf/tests/tooling.rs, schemas/development/mdsf.schema.json, schemas/v0.9.4-next/mdsf.schema.json, tools/tombi/plugin.json
Adds support for the tombi toml formatter and linter. 
Closes #1050
=> feat(tools): add support for tombi

CHANGELOG.md, codegen/src/language_to_filetype.rs, codegen/src/tools.rs, mdsf/src/commands/format.rs, mdsf/src/execution/mod.rs
Reversing if let chain usage since it is currently throwing an error with the latest clippy, even though it is stable as of yesterday
=> refactor: revert if let chain syntax

CHANGELOG.md, codegen/src/actions/packages.rs, codegen/src/language_to_filetype.rs, codegen/src/main.rs, codegen/src/tools.rs, github-action/biome.json, mdsf-vscode/biome.json, mdsf/src/commands/format.rs, mdsf/src/config.rs, mdsf/src/execution/mod.rs
Switch to chained if let syntax since it is stable
=> refactor: use chained if let syntax
